package com.hfut.entity;

public class LGraDesignWorkload extends LGraDesignWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_design.people
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    private Integer people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_design.weeks
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    private Integer weeks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_design.coefficient
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    private Float coefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_design.workload
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_design.note
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_design.people
     *
     * @return the value of local_graduate_design.people
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_design.people
     *
     * @param people the value for local_graduate_design.people
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_design.weeks
     *
     * @return the value of local_graduate_design.weeks
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public Integer getWeeks() {
        return weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_design.weeks
     *
     * @param weeks the value for local_graduate_design.weeks
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public void setWeeks(Integer weeks) {
        this.weeks = weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_design.coefficient
     *
     * @return the value of local_graduate_design.coefficient
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public Float getCoefficient() {
        return coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_design.coefficient
     *
     * @param coefficient the value for local_graduate_design.coefficient
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public void setCoefficient(Float coefficient) {
        this.coefficient = coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_design.workload
     *
     * @return the value of local_graduate_design.workload
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public Float getWorkload() {
        return workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_design.workload
     *
     * @param workload the value for local_graduate_design.workload
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public void setWorkload(Float workload) {
        this.workload = workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_design.note
     *
     * @return the value of local_graduate_design.note
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_design.note
     *
     * @param note the value for local_graduate_design.note
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}