package com.hfut.entity;

public class LGraPracticeWorkload extends LGraPracticeWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_practice.people
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    private Integer people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_practice.weeks
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    private Integer weeks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_practice.place
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_practice.workload
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_practice.note
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_practice.people
     *
     * @return the value of local_graduate_practice.people
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_practice.people
     *
     * @param people the value for local_graduate_practice.people
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_practice.weeks
     *
     * @return the value of local_graduate_practice.weeks
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    public Integer getWeeks() {
        return weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_practice.weeks
     *
     * @param weeks the value for local_graduate_practice.weeks
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    public void setWeeks(Integer weeks) {
        this.weeks = weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_practice.place
     *
     * @return the value of local_graduate_practice.place
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_practice.place
     *
     * @param place the value for local_graduate_practice.place
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_practice.workload
     *
     * @return the value of local_graduate_practice.workload
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    public Float getWorkload() {
        return workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_practice.workload
     *
     * @param workload the value for local_graduate_practice.workload
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    public void setWorkload(Float workload) {
        this.workload = workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_practice.note
     *
     * @return the value of local_graduate_practice.note
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_practice.note
     *
     * @param note the value for local_graduate_practice.note
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}