package com.hfut.entity;

public class LGraDesignWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_design.id
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_design.teacher
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_design.years
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    private Integer years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_graduate_design.grades
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    private String grades;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_design.id
     *
     * @return the value of local_graduate_design.id
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_design.id
     *
     * @param id the value for local_graduate_design.id
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_design.teacher
     *
     * @return the value of local_graduate_design.teacher
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_design.teacher
     *
     * @param teacher the value for local_graduate_design.teacher
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_design.years
     *
     * @return the value of local_graduate_design.years
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public Integer getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_design.years
     *
     * @param years the value for local_graduate_design.years
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public void setYears(Integer years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_graduate_design.grades
     *
     * @return the value of local_graduate_design.grades
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public String getGrades() {
        return grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_graduate_design.grades
     *
     * @param grades the value for local_graduate_design.grades
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    public void setGrades(String grades) {
        this.grades = grades == null ? null : grades.trim();
    }
}