package com.hfut.entity;

public class LMatchWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_match.id
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_match.teacher
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_match.years
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    private Integer years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_match.number
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    private String number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_match.id
     *
     * @return the value of local_match.id
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_match.id
     *
     * @param id the value for local_match.id
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_match.teacher
     *
     * @return the value of local_match.teacher
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_match.teacher
     *
     * @param teacher the value for local_match.teacher
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_match.years
     *
     * @return the value of local_match.years
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    public Integer getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_match.years
     *
     * @param years the value for local_match.years
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    public void setYears(Integer years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_match.number
     *
     * @return the value of local_match.number
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_match.number
     *
     * @param number the value for local_match.number
     *
     * @mbggenerated Sun Oct 29 14:23:47 CST 2017
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }
}