package com.hfut.entity;

public class LocalCourseWorkload extends LocalCourseWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_course.grades
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    private String grades;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_course.period
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    private Float period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_course.credit
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    private Float credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_course.people
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    private Integer people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_course.coefficient
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    private Float coefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_course.workload
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_course.note
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_course.grades
     *
     * @return the value of local_course.grades
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public String getGrades() {
        return grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_course.grades
     *
     * @param grades the value for local_course.grades
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public void setGrades(String grades) {
        this.grades = grades == null ? null : grades.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_course.period
     *
     * @return the value of local_course.period
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public Float getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_course.period
     *
     * @param period the value for local_course.period
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public void setPeriod(Float period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_course.credit
     *
     * @return the value of local_course.credit
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public Float getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_course.credit
     *
     * @param credit the value for local_course.credit
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public void setCredit(Float credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_course.people
     *
     * @return the value of local_course.people
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_course.people
     *
     * @param people the value for local_course.people
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_course.coefficient
     *
     * @return the value of local_course.coefficient
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public Float getCoefficient() {
        return coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_course.coefficient
     *
     * @param coefficient the value for local_course.coefficient
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public void setCoefficient(Float coefficient) {
        this.coefficient = coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_course.workload
     *
     * @return the value of local_course.workload
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public Float getWorkload() {
        return workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_course.workload
     *
     * @param workload the value for local_course.workload
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public void setWorkload(Float workload) {
        this.workload = workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_course.note
     *
     * @return the value of local_course.note
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_course.note
     *
     * @param note the value for local_course.note
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}