package com.hfut.entity;

public class LocalExpWorkload extends LocalExpWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_expriment.grades
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    private String grades;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_expriment.type
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_expriment.period
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    private Float period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_expriment.people
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    private Integer people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_expriment.load_coefficient
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    private Float loadCoefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_expriment.type_coefficient
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    private Float typeCoefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_expriment.workload
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_expriment.note
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_expriment.grades
     *
     * @return the value of local_expriment.grades
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public String getGrades() {
        return grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_expriment.grades
     *
     * @param grades the value for local_expriment.grades
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public void setGrades(String grades) {
        this.grades = grades == null ? null : grades.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_expriment.type
     *
     * @return the value of local_expriment.type
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_expriment.type
     *
     * @param type the value for local_expriment.type
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_expriment.period
     *
     * @return the value of local_expriment.period
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public Float getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_expriment.period
     *
     * @param period the value for local_expriment.period
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public void setPeriod(Float period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_expriment.people
     *
     * @return the value of local_expriment.people
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_expriment.people
     *
     * @param people the value for local_expriment.people
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_expriment.load_coefficient
     *
     * @return the value of local_expriment.load_coefficient
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public Float getLoadCoefficient() {
        return loadCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_expriment.load_coefficient
     *
     * @param loadCoefficient the value for local_expriment.load_coefficient
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public void setLoadCoefficient(Float loadCoefficient) {
        this.loadCoefficient = loadCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_expriment.type_coefficient
     *
     * @return the value of local_expriment.type_coefficient
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public Float getTypeCoefficient() {
        return typeCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_expriment.type_coefficient
     *
     * @param typeCoefficient the value for local_expriment.type_coefficient
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public void setTypeCoefficient(Float typeCoefficient) {
        this.typeCoefficient = typeCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_expriment.workload
     *
     * @return the value of local_expriment.workload
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public Float getWorkload() {
        return workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_expriment.workload
     *
     * @param workload the value for local_expriment.workload
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public void setWorkload(Float workload) {
        this.workload = workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_expriment.note
     *
     * @return the value of local_expriment.note
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_expriment.note
     *
     * @param note the value for local_expriment.note
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}