package com.hfut.entity;

public class LPracticeWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_practice.id
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_practice.college
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_practice.teacher
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_practice.years
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    private Integer years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_practice.major
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    private String major;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_practice.id
     *
     * @return the value of local_practice.id
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_practice.id
     *
     * @param id the value for local_practice.id
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_practice.college
     *
     * @return the value of local_practice.college
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_practice.college
     *
     * @param college the value for local_practice.college
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_practice.teacher
     *
     * @return the value of local_practice.teacher
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_practice.teacher
     *
     * @param teacher the value for local_practice.teacher
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_practice.years
     *
     * @return the value of local_practice.years
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    public Integer getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_practice.years
     *
     * @param years the value for local_practice.years
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    public void setYears(Integer years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_practice.major
     *
     * @return the value of local_practice.major
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_practice.major
     *
     * @param major the value for local_practice.major
     *
     * @mbggenerated Sat Oct 28 20:32:23 CST 2017
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }
}