package com.hfut.entity;

public class LProjectWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_project.id
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_project.years
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    private Integer years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_project.teacher
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_project.number
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    private String number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_project.id
     *
     * @return the value of local_project.id
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_project.id
     *
     * @param id the value for local_project.id
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_project.years
     *
     * @return the value of local_project.years
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    public Integer getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_project.years
     *
     * @param years the value for local_project.years
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    public void setYears(Integer years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_project.teacher
     *
     * @return the value of local_project.teacher
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_project.teacher
     *
     * @param teacher the value for local_project.teacher
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_project.number
     *
     * @return the value of local_project.number
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_project.number
     *
     * @param number the value for local_project.number
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }
}