package com.hfut.entity;

public class RemoteDesignWorkload extends RemoteDesignWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_design.grades
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    private String grades;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_design.weeks
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    private Integer weeks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_design.people
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    private Integer people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_design.load_coefficient
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    private Float loadCoefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_design.workload
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_design.money
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    private Float money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_design.note
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_design.grades
     *
     * @return the value of remote_design.grades
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public String getGrades() {
        return grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_design.grades
     *
     * @param grades the value for remote_design.grades
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public void setGrades(String grades) {
        this.grades = grades == null ? null : grades.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_design.weeks
     *
     * @return the value of remote_design.weeks
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public Integer getWeeks() {
        return weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_design.weeks
     *
     * @param weeks the value for remote_design.weeks
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public void setWeeks(Integer weeks) {
        this.weeks = weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_design.people
     *
     * @return the value of remote_design.people
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_design.people
     *
     * @param people the value for remote_design.people
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_design.load_coefficient
     *
     * @return the value of remote_design.load_coefficient
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public Float getLoadCoefficient() {
        return loadCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_design.load_coefficient
     *
     * @param loadCoefficient the value for remote_design.load_coefficient
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public void setLoadCoefficient(Float loadCoefficient) {
        this.loadCoefficient = loadCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_design.workload
     *
     * @return the value of remote_design.workload
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public Float getWorkload() {
        return workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_design.workload
     *
     * @param workload the value for remote_design.workload
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public void setWorkload(Float workload) {
        this.workload = workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_design.money
     *
     * @return the value of remote_design.money
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_design.money
     *
     * @param money the value for remote_design.money
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_design.note
     *
     * @return the value of remote_design.note
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_design.note
     *
     * @param note the value for remote_design.note
     *
     * @mbggenerated Thu Oct 26 13:57:14 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}