package com.hfut.entity;

public class RemoteGraduateWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_graduate.id
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_graduate.college
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_graduate.teacher
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_graduate.years
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    private Integer years;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_graduate.id
     *
     * @return the value of remote_graduate.id
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_graduate.id
     *
     * @param id the value for remote_graduate.id
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_graduate.college
     *
     * @return the value of remote_graduate.college
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_graduate.college
     *
     * @param college the value for remote_graduate.college
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_graduate.teacher
     *
     * @return the value of remote_graduate.teacher
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_graduate.teacher
     *
     * @param teacher the value for remote_graduate.teacher
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_graduate.years
     *
     * @return the value of remote_graduate.years
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public Integer getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_graduate.years
     *
     * @param years the value for remote_graduate.years
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public void setYears(Integer years) {
        this.years = years;
    }
}