package com.hfut.entity;

public class RemoteTeachWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.id
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.college
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.teacher
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.lesson
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private String lesson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.years
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Integer years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.teach_class
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Integer teachClass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.id
     *
     * @return the value of remote_teach_workload.id
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.id
     *
     * @param id the value for remote_teach_workload.id
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.college
     *
     * @return the value of remote_teach_workload.college
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.college
     *
     * @param college the value for remote_teach_workload.college
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.teacher
     *
     * @return the value of remote_teach_workload.teacher
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.teacher
     *
     * @param teacher the value for remote_teach_workload.teacher
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.lesson
     *
     * @return the value of remote_teach_workload.lesson
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public String getLesson() {
        return lesson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.lesson
     *
     * @param lesson the value for remote_teach_workload.lesson
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setLesson(String lesson) {
        this.lesson = lesson == null ? null : lesson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.years
     *
     * @return the value of remote_teach_workload.years
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Integer getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.years
     *
     * @param years the value for remote_teach_workload.years
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setYears(Integer years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.teach_class
     *
     * @return the value of remote_teach_workload.teach_class
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Integer getTeachClass() {
        return teachClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.teach_class
     *
     * @param teachClass the value for remote_teach_workload.teach_class
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setTeachClass(Integer teachClass) {
        this.teachClass = teachClass;
    }
}