package com.hfut.entity;

public class RemoteExprementWorkload extends RemoteExprementWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_expriment.grades
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    private String grades;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_expriment.period
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    private Float period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_expriment.people
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    private Integer people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_expriment.re_coefficient
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    private Float reCoefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_expriment.type_coefficient
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    private Float typeCoefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_expriment.workload
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_expriment.money
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    private Float money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_expriment.note
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_expriment.grades
     *
     * @return the value of remote_expriment.grades
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public String getGrades() {
        return grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_expriment.grades
     *
     * @param grades the value for remote_expriment.grades
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public void setGrades(String grades) {
        this.grades = grades == null ? null : grades.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_expriment.period
     *
     * @return the value of remote_expriment.period
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public Float getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_expriment.period
     *
     * @param period the value for remote_expriment.period
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public void setPeriod(Float period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_expriment.people
     *
     * @return the value of remote_expriment.people
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_expriment.people
     *
     * @param people the value for remote_expriment.people
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_expriment.re_coefficient
     *
     * @return the value of remote_expriment.re_coefficient
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public Float getReCoefficient() {
        return reCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_expriment.re_coefficient
     *
     * @param reCoefficient the value for remote_expriment.re_coefficient
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public void setReCoefficient(Float reCoefficient) {
        this.reCoefficient = reCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_expriment.type_coefficient
     *
     * @return the value of remote_expriment.type_coefficient
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public Float getTypeCoefficient() {
        return typeCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_expriment.type_coefficient
     *
     * @param typeCoefficient the value for remote_expriment.type_coefficient
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public void setTypeCoefficient(Float typeCoefficient) {
        this.typeCoefficient = typeCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_expriment.workload
     *
     * @return the value of remote_expriment.workload
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public Float getWorkload() {
        return workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_expriment.workload
     *
     * @param workload the value for remote_expriment.workload
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public void setWorkload(Float workload) {
        this.workload = workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_expriment.money
     *
     * @return the value of remote_expriment.money
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_expriment.money
     *
     * @param money the value for remote_expriment.money
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_expriment.note
     *
     * @return the value of remote_expriment.note
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_expriment.note
     *
     * @param note the value for remote_expriment.note
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}