package com.hfut.entity;

public class RemoteGraduateWorkload extends RemoteGraduateWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_graduate.grades
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    private String grades;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_graduate.people
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    private Integer people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_graduate.weeks
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    private Integer weeks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_graduate.workload
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_graduate.money
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    private Float money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_graduate.note
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_graduate.grades
     *
     * @return the value of remote_graduate.grades
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public String getGrades() {
        return grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_graduate.grades
     *
     * @param grades the value for remote_graduate.grades
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public void setGrades(String grades) {
        this.grades = grades == null ? null : grades.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_graduate.people
     *
     * @return the value of remote_graduate.people
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_graduate.people
     *
     * @param people the value for remote_graduate.people
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_graduate.weeks
     *
     * @return the value of remote_graduate.weeks
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public Integer getWeeks() {
        return weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_graduate.weeks
     *
     * @param weeks the value for remote_graduate.weeks
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public void setWeeks(Integer weeks) {
        this.weeks = weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_graduate.workload
     *
     * @return the value of remote_graduate.workload
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public Float getWorkload() {
        return workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_graduate.workload
     *
     * @param workload the value for remote_graduate.workload
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public void setWorkload(Float workload) {
        this.workload = workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_graduate.money
     *
     * @return the value of remote_graduate.money
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_graduate.money
     *
     * @param money the value for remote_graduate.money
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_graduate.note
     *
     * @return the value of remote_graduate.note
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_graduate.note
     *
     * @param note the value for remote_graduate.note
     *
     * @mbggenerated Thu Oct 26 20:03:52 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}