package com.hfut.entity;

public class RemoteTeachWorkload extends RemoteTeachWorkloadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.grades
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private String grades;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.period
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Float period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.credit
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Float credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.people
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Integer people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.class_coefficient
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Float classCoefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.money
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Float money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_teach_workload.note
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.grades
     *
     * @return the value of remote_teach_workload.grades
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public String getGrades() {
        return grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.grades
     *
     * @param grades the value for remote_teach_workload.grades
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setGrades(String grades) {
        this.grades = grades == null ? null : grades.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.period
     *
     * @return the value of remote_teach_workload.period
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Float getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.period
     *
     * @param period the value for remote_teach_workload.period
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setPeriod(Float period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.credit
     *
     * @return the value of remote_teach_workload.credit
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Float getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.credit
     *
     * @param credit the value for remote_teach_workload.credit
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setCredit(Float credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.people
     *
     * @return the value of remote_teach_workload.people
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.people
     *
     * @param people the value for remote_teach_workload.people
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.class_coefficient
     *
     * @return the value of remote_teach_workload.class_coefficient
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Float getClassCoefficient() {
        return classCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.class_coefficient
     *
     * @param classCoefficient the value for remote_teach_workload.class_coefficient
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setClassCoefficient(Float classCoefficient) {
        this.classCoefficient = classCoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.workload
     *
     * @return the value of remote_teach_workload.workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Float getWorkload() {
        return workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.workload
     *
     * @param workload the value for remote_teach_workload.workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setWorkload(Float workload) {
        this.workload = workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.money
     *
     * @return the value of remote_teach_workload.money
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.money
     *
     * @param money the value for remote_teach_workload.money
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_teach_workload.note
     *
     * @return the value of remote_teach_workload.note
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_teach_workload.note
     *
     * @param note the value for remote_teach_workload.note
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}