package com.hfut.entity;

public class WorkLoad {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workload.id
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workload.teacher
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workload.lesson
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private String lesson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workload.grades
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private String grades;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workload.teach_class
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Integer teachClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workload.period
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workload.years
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Integer years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workload.people
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Integer people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workload.coefficient
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Float coefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workload.workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workload.money
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    private Float money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workload.id
     *
     * @return the value of workload.id
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workload.id
     *
     * @param id the value for workload.id
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workload.teacher
     *
     * @return the value of workload.teacher
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workload.teacher
     *
     * @param teacher the value for workload.teacher
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workload.lesson
     *
     * @return the value of workload.lesson
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public String getLesson() {
        return lesson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workload.lesson
     *
     * @param lesson the value for workload.lesson
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setLesson(String lesson) {
        this.lesson = lesson == null ? null : lesson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workload.grades
     *
     * @return the value of workload.grades
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public String getGrades() {
        return grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workload.grades
     *
     * @param grades the value for workload.grades
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setGrades(String grades) {
        this.grades = grades == null ? null : grades.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workload.teach_class
     *
     * @return the value of workload.teach_class
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Integer getTeachClass() {
        return teachClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workload.teach_class
     *
     * @param teachClass the value for workload.teach_class
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setTeachClass(Integer teachClass) {
        this.teachClass = teachClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workload.period
     *
     * @return the value of workload.period
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workload.period
     *
     * @param period the value for workload.period
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workload.years
     *
     * @return the value of workload.years
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Integer getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workload.years
     *
     * @param years the value for workload.years
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setYears(Integer years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workload.people
     *
     * @return the value of workload.people
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workload.people
     *
     * @param people the value for workload.people
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workload.coefficient
     *
     * @return the value of workload.coefficient
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Float getCoefficient() {
        return coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workload.coefficient
     *
     * @param coefficient the value for workload.coefficient
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setCoefficient(Float coefficient) {
        this.coefficient = coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workload.workload
     *
     * @return the value of workload.workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Float getWorkload() {
        return workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workload.workload
     *
     * @param workload the value for workload.workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setWorkload(Float workload) {
        this.workload = workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workload.money
     *
     * @return the value of workload.money
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workload.money
     *
     * @param money the value for workload.money
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    public void setMoney(Float money) {
        this.money = money;
    }
}