{"status":"success",
"result":[
{"name":"体育",
"links":[
{"name":"Google","url":"http://www.google.com"},
{"name":"Baidu","url":"http://www.baidu.com"},
{"name":"SoSo","url":"http://www.SoSo.com"}
]
},
{"name":"娱乐",
"links":[
{"name":"Google","url":"http://www.google.com"},
{"name":"Baidu","url":"http://www.baidu.com"},
{"name":"SoSo","url":"http://www.SoSo.com"}
]
},
{"name":"时事",
"links":[
{"name":"Google","url":"http://www.google.com"}
,{"name":"Baidu","url":"http://www.baidu.com"},
{"name":"SoSo","url":"http://www.SoSo.com"}
]
}
]
}