package com.hfut.mapper;

import com.hfut.entity.LGraPracticeWorkload;
import com.hfut.entity.LGraPracticeWorkloadExample;
import com.hfut.entity.LGraPracticeWorkloadKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LGraPracticeWorkloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_practice
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    int countByExample(LGraPracticeWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_practice
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    int deleteByExample(LGraPracticeWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_practice
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    int deleteByPrimaryKey(LGraPracticeWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_practice
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    int insert(LGraPracticeWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_practice
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    int insertSelective(LGraPracticeWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_practice
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    List<LGraPracticeWorkload> selectByExample(LGraPracticeWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_practice
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    LGraPracticeWorkload selectByPrimaryKey(LGraPracticeWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_practice
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") LGraPracticeWorkload record, @Param("example") LGraPracticeWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_practice
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    int updateByExample(@Param("record") LGraPracticeWorkload record, @Param("example") LGraPracticeWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_practice
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    int updateByPrimaryKeySelective(LGraPracticeWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_practice
     *
     * @mbggenerated Fri Oct 27 22:19:48 CST 2017
     */
    int updateByPrimaryKey(LGraPracticeWorkload record);
}