package com.hfut.mapper;

import com.hfut.entity.LGraDesignWorkload;
import com.hfut.entity.LGraDesignWorkloadExample;
import com.hfut.entity.LGraDesignWorkloadKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LGraDesignWorkloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_design
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    int countByExample(LGraDesignWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_design
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    int deleteByExample(LGraDesignWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_design
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    int deleteByPrimaryKey(LGraDesignWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_design
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    int insert(LGraDesignWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_design
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    int insertSelective(LGraDesignWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_design
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    List<LGraDesignWorkload> selectByExample(LGraDesignWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_design
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    LGraDesignWorkload selectByPrimaryKey(LGraDesignWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_design
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") LGraDesignWorkload record, @Param("example") LGraDesignWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_design
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    int updateByExample(@Param("record") LGraDesignWorkload record, @Param("example") LGraDesignWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_design
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    int updateByPrimaryKeySelective(LGraDesignWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_graduate_design
     *
     * @mbggenerated Sat Oct 28 16:26:20 CST 2017
     */
    int updateByPrimaryKey(LGraDesignWorkload record);
}