package com.hfut.mapper;

import com.hfut.entity.LNetWorkload;
import com.hfut.entity.LNetWorkloadExample;
import com.hfut.entity.LNetWorkloadKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LNetWorkloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_net
     *
     * @mbggenerated Sat Oct 28 13:53:52 CST 2017
     */
    int countByExample(LNetWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_net
     *
     * @mbggenerated Sat Oct 28 13:53:52 CST 2017
     */
    int deleteByExample(LNetWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_net
     *
     * @mbggenerated Sat Oct 28 13:53:52 CST 2017
     */
    int deleteByPrimaryKey(LNetWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_net
     *
     * @mbggenerated Sat Oct 28 13:53:52 CST 2017
     */
    int insert(LNetWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_net
     *
     * @mbggenerated Sat Oct 28 13:53:52 CST 2017
     */
    int insertSelective(LNetWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_net
     *
     * @mbggenerated Sat Oct 28 13:53:52 CST 2017
     */
    List<LNetWorkload> selectByExample(LNetWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_net
     *
     * @mbggenerated Sat Oct 28 13:53:52 CST 2017
     */
    LNetWorkload selectByPrimaryKey(LNetWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_net
     *
     * @mbggenerated Sat Oct 28 13:53:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") LNetWorkload record, @Param("example") LNetWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_net
     *
     * @mbggenerated Sat Oct 28 13:53:52 CST 2017
     */
    int updateByExample(@Param("record") LNetWorkload record, @Param("example") LNetWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_net
     *
     * @mbggenerated Sat Oct 28 13:53:52 CST 2017
     */
    int updateByPrimaryKeySelective(LNetWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_net
     *
     * @mbggenerated Sat Oct 28 13:53:52 CST 2017
     */
    int updateByPrimaryKey(LNetWorkload record);
}