package com.hfut.mapper;

import com.hfut.entity.LocalCourseWorkload;
import com.hfut.entity.LocalCourseWorkloadExample;
import com.hfut.entity.LocalCourseWorkloadKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocalCourseWorkloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_course
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    int countByExample(LocalCourseWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_course
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    int deleteByExample(LocalCourseWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_course
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    int deleteByPrimaryKey(LocalCourseWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_course
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    int insert(LocalCourseWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_course
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    int insertSelective(LocalCourseWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_course
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    List<LocalCourseWorkload> selectByExample(LocalCourseWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_course
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    LocalCourseWorkload selectByPrimaryKey(LocalCourseWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_course
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") LocalCourseWorkload record, @Param("example") LocalCourseWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_course
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    int updateByExample(@Param("record") LocalCourseWorkload record, @Param("example") LocalCourseWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_course
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    int updateByPrimaryKeySelective(LocalCourseWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_course
     *
     * @mbggenerated Fri Oct 27 13:31:00 CST 2017
     */
    int updateByPrimaryKey(LocalCourseWorkload record);
}