package com.hfut.mapper;

import com.hfut.entity.LocalExpWorkload;
import com.hfut.entity.LocalExpWorkloadExample;
import com.hfut.entity.LocalExpWorkloadKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LocalExpWorkloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_expriment
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    int countByExample(LocalExpWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_expriment
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    int deleteByExample(LocalExpWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_expriment
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    int deleteByPrimaryKey(LocalExpWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_expriment
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    int insert(LocalExpWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_expriment
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    int insertSelective(LocalExpWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_expriment
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    List<LocalExpWorkload> selectByExample(LocalExpWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_expriment
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    LocalExpWorkload selectByPrimaryKey(LocalExpWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_expriment
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") LocalExpWorkload record, @Param("example") LocalExpWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_expriment
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    int updateByExample(@Param("record") LocalExpWorkload record, @Param("example") LocalExpWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_expriment
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    int updateByPrimaryKeySelective(LocalExpWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_expriment
     *
     * @mbggenerated Fri Oct 27 16:45:34 CST 2017
     */
    int updateByPrimaryKey(LocalExpWorkload record);
}