package com.hfut.mapper;

import com.hfut.entity.LocalDesignWorkload;
import com.hfut.entity.LocalDesignWorkloadExample;
import com.hfut.entity.LocalDesignWorkloadKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LocalDesignWorkloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_design
     *
     * @mbggenerated Fri Oct 27 21:03:30 CST 2017
     */
    int countByExample(LocalDesignWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_design
     *
     * @mbggenerated Fri Oct 27 21:03:30 CST 2017
     */
    int deleteByExample(LocalDesignWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_design
     *
     * @mbggenerated Fri Oct 27 21:03:30 CST 2017
     */
    int deleteByPrimaryKey(LocalDesignWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_design
     *
     * @mbggenerated Fri Oct 27 21:03:30 CST 2017
     */
    int insert(LocalDesignWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_design
     *
     * @mbggenerated Fri Oct 27 21:03:30 CST 2017
     */
    int insertSelective(LocalDesignWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_design
     *
     * @mbggenerated Fri Oct 27 21:03:30 CST 2017
     */
    List<LocalDesignWorkload> selectByExample(LocalDesignWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_design
     *
     * @mbggenerated Fri Oct 27 21:03:30 CST 2017
     */
    LocalDesignWorkload selectByPrimaryKey(LocalDesignWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_design
     *
     * @mbggenerated Fri Oct 27 21:03:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") LocalDesignWorkload record, @Param("example") LocalDesignWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_design
     *
     * @mbggenerated Fri Oct 27 21:03:30 CST 2017
     */
    int updateByExample(@Param("record") LocalDesignWorkload record, @Param("example") LocalDesignWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_design
     *
     * @mbggenerated Fri Oct 27 21:03:30 CST 2017
     */
    int updateByPrimaryKeySelective(LocalDesignWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_design
     *
     * @mbggenerated Fri Oct 27 21:03:30 CST 2017
     */
    int updateByPrimaryKey(LocalDesignWorkload record);
}