package com.hfut.mapper;

import com.hfut.entity.LProjectWorkload;
import com.hfut.entity.LProjectWorkloadExample;
import com.hfut.entity.LProjectWorkloadKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LProjectWorkloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_project
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    int countByExample(LProjectWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_project
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    int deleteByExample(LProjectWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_project
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    int deleteByPrimaryKey(LProjectWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_project
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    int insert(LProjectWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_project
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    int insertSelective(LProjectWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_project
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    List<LProjectWorkload> selectByExample(LProjectWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_project
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    LProjectWorkload selectByPrimaryKey(LProjectWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_project
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") LProjectWorkload record, @Param("example") LProjectWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_project
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    int updateByExample(@Param("record") LProjectWorkload record, @Param("example") LProjectWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_project
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    int updateByPrimaryKeySelective(LProjectWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_project
     *
     * @mbggenerated Sat Oct 28 21:14:11 CST 2017
     */
    int updateByPrimaryKey(LProjectWorkload record);
}