package com.hfut.mapper;

import com.hfut.entity.RemoteExpWorkload;
import com.hfut.entity.RemoteExpWorkloadExample;
import com.hfut.entity.RemoteExpWorkloadKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RemoteExpWorkloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int countByExample(RemoteExpWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int deleteByExample(RemoteExpWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int deleteByPrimaryKey(RemoteExpWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int insert(RemoteExpWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int insertSelective(RemoteExpWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    List<RemoteExpWorkload> selectByExample(RemoteExpWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    RemoteExpWorkload selectByPrimaryKey(RemoteExpWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") RemoteExpWorkload record, @Param("example") RemoteExpWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByExample(@Param("record") RemoteExpWorkload record, @Param("example") RemoteExpWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByPrimaryKeySelective(RemoteExpWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByPrimaryKey(RemoteExpWorkload record);
}