package com.hfut.mapper;

import com.hfut.entity.RemoteTeachWorkload;
import com.hfut.entity.RemoteTeachWorkloadExample;
import com.hfut.entity.RemoteTeachWorkloadKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RemoteTeachWorkloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_teach_workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int countByExample(RemoteTeachWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_teach_workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int deleteByExample(RemoteTeachWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_teach_workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int deleteByPrimaryKey(RemoteTeachWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_teach_workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int insert(RemoteTeachWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_teach_workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int insertSelective(RemoteTeachWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_teach_workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    List<RemoteTeachWorkload> selectByExample(RemoteTeachWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_teach_workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    RemoteTeachWorkload selectByPrimaryKey(RemoteTeachWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_teach_workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") RemoteTeachWorkload record, @Param("example") RemoteTeachWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_teach_workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByExample(@Param("record") RemoteTeachWorkload record, @Param("example") RemoteTeachWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_teach_workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByPrimaryKeySelective(RemoteTeachWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_teach_workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByPrimaryKey(RemoteTeachWorkload record);
}