package com.hfut.mapper;

import com.hfut.entity.RemoteExprementWorkload;
import com.hfut.entity.RemoteExprementWorkloadExample;
import com.hfut.entity.RemoteExprementWorkloadKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RemoteExprementWorkloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    int countByExample(RemoteExprementWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    int deleteByExample(RemoteExprementWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    int deleteByPrimaryKey(RemoteExprementWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    int insert(RemoteExprementWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    int insertSelective(RemoteExprementWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    List<RemoteExprementWorkload> selectByExample(RemoteExprementWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    RemoteExprementWorkload selectByPrimaryKey(RemoteExprementWorkloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") RemoteExprementWorkload record, @Param("example") RemoteExprementWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    int updateByExample(@Param("record") RemoteExprementWorkload record, @Param("example") RemoteExprementWorkloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    int updateByPrimaryKeySelective(RemoteExprementWorkload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote_expriment
     *
     * @mbggenerated Thu Oct 26 09:17:38 CST 2017
     */
    int updateByPrimaryKey(RemoteExprementWorkload record);
}