package com.hfut.mapper;

import com.hfut.entity.WorkLoad;
import com.hfut.entity.WorkLoadExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WorkLoadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int countByExample(WorkLoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int deleteByExample(WorkLoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int insert(WorkLoad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int insertSelective(WorkLoad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    List<WorkLoad> selectByExample(WorkLoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    WorkLoad selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") WorkLoad record, @Param("example") WorkLoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByExample(@Param("record") WorkLoad record, @Param("example") WorkLoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByPrimaryKeySelective(WorkLoad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workload
     *
     * @mbggenerated Thu Oct 26 09:44:31 CST 2017
     */
    int updateByPrimaryKey(WorkLoad record);
}